# Generated by Django 5.2.5 on 2026-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Satın Al Linki'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Öne Çıkar'),
        ),
    ]
