# Generated by Django 5.2.5 on 2026-02-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_created_at_alter_product_external_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_url',
        ),
    ]
